### ISSUE TITLE
能配网成功,但是手机这边收不到任何数据

### ISSUE THREAD

**Issue by hysgit** [chengxinping/AirKissDemo#1]
最终结果就是手机这边得不到设备配网成功的信息

**Comment by chengxinping** [comment]
README.md里面有注释，一般是来说这个需要与硬件配合，你给硬件配网成功后硬件是什么方式告诉你配网成功，我们这边的处理是硬件联网成功会发送一段UDP广播，demo里面有简单的接受UDP，然后转成string.
